plugins {
    id 'com.android.application'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.libremobileos.dynamicwallpaper"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    namespace 'com.libremobileos.dynamicwallpaper'
}

dependencies {
    implementation('androidx.appcompat:appcompat:1.6.1') {
        exclude group: 'org.jetbrains.kotlin'
    }
    implementation('androidx.core:core-ktx:1.12.0') {
        exclude group: 'org.jetbrains.kotlin'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}